INSERT INTO Lookup_EU (countrycode, countryname) VALUES
('AT', 'Austria'),
('BE', 'Belgium'),
('BG', 'Bulgaria'),
('HR', 'Croatia'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('EE', 'Estonia'),
('FI', 'Finland'),
('FR', 'France'),
('DE', 'Germany'),
('EL', 'Greece'),
('HU', 'Hungary'),
('IE', 'Ireland'),
('IT', 'Italy'),
('LV', 'Latvia'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MT', 'Malta'),
('NL', 'Netherlands'),
('PL', 'Poland'),
('PT', 'Portugal'),
('RO', 'Romania'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('ES', 'Spain'),
('SE', 'Sweden');
